name: Verify

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0
      - name: Set up Golang
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: "1.23.7"
          check-latest: true
#      - name: Lint
#        run: go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.0.2 run ./...
      - name: Build Server
        run: go build -o server ./main.go
      - name: Build Test Runner
        run: go build -o runner ./test/main.go